pipeline:
  name: Build harnessdemo
  identifier: Build_aedifex_harnessdemo_1711406286300
  projectIdentifier: default_project
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Echo Welcome Message
                  identifier: Echo_Welcome_Message
                  spec:
                    shell: Sh
                    command: echo "Welcome to Harness CI"
              - step:
                  type: Run
                  name: Echo 2
                  identifier: Echo_2
                  spec:
                    shell: Sh
                    command: env
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1711406225860
        repoName: aedifex/harnessdemo
        build: <+input>
